apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: anthos
  labels:
    app: anthos
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    configDigest: {{ .Values.config_digest }}
spec:
  secretName: letsencrypt-tls-crt
  issuerRef:
    name: anthos
  commonName: {{ .Values.domain }}
  dnsNames: []
  acme:
    config:
      - http01:
          # Name of the ingress that is going to be used to solve ACME challenges
          ingress: anthos
        domains:
          - {{ .Values.domain }}
