apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  labels:
    app: jaeger
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    jaeger-infra: agent-service
spec:
  type: NodePort
  ports:
    - name: agent-zipkin-thrift
      port: 0000
      protocol: UDP
      targetPort: 0000
    - name: agent-compact
      port: 0000
      protocol: UDP
      targetPort: 0000
    - name: agent-binary
      port: 0000
      protocol: UDP
      targetPort: 0000
  selector:
    jaeger-infra: jaeger-pod
