apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  labels:
    app: jaeger
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    jaeger-infra: collector-service
spec:
  type: NodePort
  ports:
    - name: jaeger-collector-tchannel
      port: 0000
      protocol: TCP
      targetPort: 00000
    - name: jaeger-collector-http
      port: 00000
      protocol: TCP
      targetPort: 00000
    - name: jaeger-collector-zipkin
      port: 0000
      protocol: TCP
      targetPort: 0000
  selector:
    jaeger-infra: jaeger-pod
