apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    serviceHash: {{ .Values.image.tag }}
    jaeger-infra: jaeger
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jaeger
        release: {{ .Release.Name }}
        jaeger-infra: jaeger-pod
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:{{ .Values.image.tag }}
          ports:
            - containerPort: 0000
              protocol: UDP
            - containerPort: 0000
              protocol: UDP
            - containerPort: 0000
              protocol: UDP
            - containerPort: 0000
              protocol: TCP
            - containerPort: 0000
              protocol: TCP
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "0000"
          readinessProbe:
            httpGet:
              path: "/"
              port: 0000
            initialDelaySeconds: 5

        - name: auth-proxy
          image: nginx:alpine
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: jaeger-proxy-config
              readOnly: true

            - name: jaeger-proxy-htpasswd
              mountPath: /etc/nginx/auth
              readOnly: true

      volumes:
        - name: jaeger-proxy-config
          configMap:
             name: jaeger-proxy
             items:
              - key: config
                path:  default.conf
        - name: jaeger-proxy-htpasswd
          secret:
            secretName: jaeger
