apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-proxy
  labels:
    app: jaeger-proxy
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    serviceHash: {{ .Values.image.tag }}
    jaeger-infra: jaeger-proxy
data:
  config: |-
    upstream target_server {
          server localhost:16686;
    }

    server {
        listen 80;
        # server_name SERVER_NAME;

        location / {
            auth_basic            "Protected";
            auth_basic_user_file  /etc/nginx/auth/htpasswd;
            proxy_pass            http://target_server;
            proxy_read_timeout    10;
            proxy_http_version    1.1;
            proxy_set_header      Connection "";
            proxy_set_header      Authorization "";
            proxy_redirect        off;
            proxy_buffering       off;
            proxy_set_header      Host            $host;
            proxy_set_header      X-Real-IP       $remote_addr;
            proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

