apiVersion: v1
kind: Service
metadata:
  name: jaeger-zipkin
  labels:
    app: jaeger
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    jaeger-infra: zipkin-service
spec:
  ports:
  - name: jaeger-collector-zipkin
    port: 0000
    protocol: TCP
    targetPort: 0000
  clusterIP: None
  selector:
    jaeger-infra: jaeger-pod
