apiVersion: v1
kind: Secret
metadata:
  name: mailhog
  labels:
    app: mailhog
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  mh_outgoing_smtp_config.json: |-
    {{ include (print $.Template.BasePath "/config/_outgoing-smtp.json.tpl") . | b64enc }}
