apiVersion: v1
kind: ConfigMap
metadata:
  name: anthos-db-config
  labels:
    app: anthos
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    configDigest: {{ .Values.config_digest }}
data:
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_CONFIG: {{ .Values.db.config | quote }}
  DB_USE_SSL: {{ .Values.db.use_ssl | quote }}
  DB_USER: {{ .Values.db.user | quote }}
  DEFAULT_DB: {{ .Values.db.default_db | quote }}
  INSTANCE_CONNECTION_NAME: {{ .Values.db.instance_connection_name | quote }}
