apiVersion: v1
kind: ConfigMap
metadata:
  name: anthos-hydra-xyz-mobile-client-config
  labels:
    app: anthos
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    configDigest: {{ .Values.config_digest }}
data:
  HYDRA_xyz_MOBILE_OAUTH2_CLIENT_ID: {{ .Values.oauth_client.xyz_mobile.id | quote }}
