apiVersion: v1
kind: Secret
metadata:
  name: admin
  labels:
    app: admin
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  super_admin_access_token: {{ .Values.admin.super_admin_access_token | b64enc | quote }}
  session_secret_key_base: {{ .Values.admin.session.secret_key_base | b64enc | quote }}
  oauth_google_client_id: {{ .Values.admin.oauth.google_client_id | b64enc | quote }}
  oauth_google_client_secret: {{ .Values.admin.oauth.google_client_secret | b64enc | quote }}
  google_application_credentials.json: {{ .Values.admin.google_application_credentials_json | b64enc | quote }}
  fastly_api_key: {{ .Values.admin.fastly_api_key | b64enc | quote }}
  sidekiq_redis_url: {{ .Values.admin.sidekiq_redis_url | b64enc | quote }}
