apiVersion: v1
kind: Secret
metadata:
  name: anthos
  labels:
    app: anthos
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    configDigest: {{ .Values.config_digest }}
type: Opaque
data:
  db_password: {{ .Values.anthos.db.password | b64enc | quote }}
  hydra_xyz_mobile_oauth2_client_secret: {{ .Values.anthos.oauth_client.xyz_mobile.secret | b64enc | quote }}
  hydra_xyz_oauth2_consent_app_secret: {{ .Values.anthos.oauth_client.consent_app.secret | b64enc | quote }}
  hydra_test_partner_oauth2_client_secret: {{ .Values.anthos.oauth_client.test_partner.secret | b64enc | quote }}
  hydra_test_affiliate_partner_app_client_secret: {{ .Values.anthos.oauth_client.affiliate_partner.secret | b64enc | quote }}
  sentry_dns: {{ .Values.anthos.sentry_dns | b64enc | quote }}
  sql_sa_credentials.json: {{ .Values.anthos.sql_sa_credentials_json | b64enc | quote }}
