apiVersion: v1
kind: Secret
metadata:
  name: docs
  labels:
    app: docs
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  docs_password: {{ .Values.docs.docs_password | b64enc | quote }}
