apiVersion: v1
kind: Secret
metadata:
  name: fiat-purchase
  labels:
    app: fiat-purchase
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  simplex_api_key: {{ .Values.fiat_purchase.simplex_api_key | b64enc | quote }}
  redis_url: {{ .Values.fiat_purchase.redis_url | b64enc | quote }}
