apiVersion: v1
kind: Secret
metadata:
  name: hydra
  labels:
    app: hydra
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  force_root_client_credentials: {{ .Values.hydra.force_root_client_credentials | b64enc | quote }}
  system_secret: {{ .Values.hydra.system_secret | b64enc | quote }}
  cluster_id: {{ .Values.hydra.cluster_id | b64enc | quote }}
  cluster_secret: {{ .Values.hydra.cluster_secret | b64enc | quote }}
