apiVersion: v1
kind: Secret
metadata:
  name: key-manager
  labels:
    app: key-manager
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  envelope_key: {{ .Values.key_manager.envelope_key | b64enc | quote }}
  upload_key: {{ .Values.key_manager.upload_key | b64enc | quote }}
  km_sa_json: {{ .Values.key_manager.km_sa_json | b64enc | quote }}
