apiVersion: v1
kind: Secret
metadata:
  name: merchant
  labels:
    app: merchant
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  cipher_master_key: {{ .Values.merchant.cipher_master_key | b64enc | quote }}
