apiVersion: v1
kind: Secret
metadata:
  name: node-wrappers
  labels:
    app: node-wrappers
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  etherscan_api_token: {{ .Values.node_wrappers.ethereum.etherscan_api_token | b64enc | quote }}
