apiVersion: v1
kind: Secret
metadata:
  name: oauth
  labels:
    app: oauth
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  redis_url: {{ .Values.oauth.redis_url | b64enc | quote }}
  session_secret: {{ .Values.oauth.session_secret | b64enc | quote }}
  session_key: {{ .Values.oauth.session_key | b64enc | quote }}
