apiVersion: v1
kind: Secret
metadata:
  name: stackdriver
  labels:
    app: stackdriver
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    configDigest: {{ .Values.config_digest }}
type: Opaque
data:
  google_stackdriver_service_account_json: {{ .Values.stackdriver.google_stackdriver_service_account_json | b64enc | quote }}
