apiVersion: v1
kind: Secret
metadata:
  name: user-profile
  labels:
    app: user-profile
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  redis_url: {{ .Values.user_profile.redis_url | b64enc | quote }}
